### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by shirshak55** [openssh-rust/openssh-sftp-client#1]
I looked on tests but it seems to require  binaries like openssh-server or openssh-client? Is it possible to use this in windows?

My use case is uploading files from windows machine to Linux in Rust Program.  Especially I had concerns if the following will even work in windows?

```
pub async fn launch_sftp() -> (process::Child, PipeWrite, PipeRead) {
    let mut child = process::Command::new(get_sftp_path())
        .args(&["-e", "-l", "DEBUG"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .kill_on_drop(true)
        .spawn()
        .unwrap();

    let stdin = child_stdin_to_pipewrite(child.stdin.take().unwrap()).unwrap();
    let stdout = child_stdout_to_pipewrite(child.stdout.take().unwrap()).unwrap();

    (child, stdin, stdout)
}

pub fn get_sftp_path() -> &'static path::Path {
    static SFTP_PATH: OnceCell<path::PathBuf> = OnceCell::new();

    SFTP_PATH.get_or_init(|| {
        let mut sftp_path: path::PathBuf = env::var("OUT_DIR").unwrap().into();
        sftp_path.push("openssh-portable");
        sftp_path.push("sftp-server");

        eprintln!("sftp_path = {:#?}", sftp_path);

        sftp_path
    })
}

```

Where does  openssh-portable  in  `sftp_path.push("openssh-portable")` comes? Can we link it statically like sqlite3 etc.?

**Comment by NobodyXu** [comment]
In principle, `openssh-sftp-client` should be able to support any platform.

Currently, the API [`lowlevel::connect`] only accepts pipe, which is only available on unix.

I planned to refactor its API to use generics and trait instead so you shall be able to use it on any platform.

> My use case is uploading files from windows machine to Linux in Rust Program. Especially I had concerns if the following will even work in windows?

Are you uploading file from local windows machine to remote linux machine?

Then you would need to establish a ssh connection to it.

[`lowlevel::connect`]: https://docs.rs/openssh-sftp-client/0.7.3/openssh_sftp_client/lowlevel/fn.connect.html

**Comment by shirshak55** [comment]
@NobodyXu I see.

Yes I am uploading file from local window machine to remote linux machine. My mom isn't that technical and she only know how to use excel. I was thinking of providing binary to her that will just upload excel file to remote linux server.  Looks like using openssh is kinda challenging :D

**Comment by NobodyXu** [comment]
@NobodyXu  It is entirely possible.

With WSL (windows subsystem for Linux), you can launch a binary to run in the WSL from windows directly.

Then, you will be able to use [`sftp` support in openssh](https://github.com/openssh-rust/openssh/pull/30) to do the job.

**Comment by shirshak55** [comment]
@NobodyXu Thanks!. But, imho, I would never setup wsl or wsl2 just for uploading file :) Wsl1 + wsl2 wastes too much cpu cycle and ram for simple things like this.

**Comment by NobodyXu** [comment]
@shirshak55 I have released v0.8.2, containing the change required to use Windows.

It also has passed CI which build this crate on Windows

**Comment by shirshak55** [comment]
@NobodyXu 

I did try but it seems ssh2 being sync library has its own problem?

https://github.com/shirshak55/rust_file_upload_experiments/blob/main/src/main.rs#L80

**Comment by NobodyXu** [comment]
@shirshak55 
`openssh-sftp-client` takes stdin and stdout of the `sftp-server` launched at remote.

I realized that `ssh2` is a sync library, using it with `openssh-sftp-client` is possible but it is not `async` anymore.

You can use `tokio::process` to spawn a ssh instance `ssh -s host sftp` where `-s` enables subsystem.

The `ChildStdin` and `ChildStdout` can then be fed into `openssh-sftp-client`.

Check [this](https://github.com/NobodyXu/openssh-rs/blob/9467a8476c5f37491dc43617b67cc32e15e12dfe/src/process_impl/session.rs#L121) for how `openssh` launches `sftp-server`.

**Comment by shirshak55** [comment]
@NobodyXu btw I was abit confused. Whats the difference between this library and https://docs.rs/ssh2/latest/ssh2/struct.Session.html#method.sftp. They seem to be doing same thing? (Except sync and async and I found this library to get async version).

**Comment by NobodyXu** [comment]
There are a few differences beside `async`:
 - This crate is written in 100% pure Rust, with a little bit of `unsafe` rust in this crate.
 - This crate models its API after `std::fs` and `tokio::fs`, which IMHO is much easier to use than `ssh2`'s sftp API.
 - This crate is generic, it can be used with any ssh implementation, while `ssh2`'s sftp has to be used with their own ssh implementation.

**Comment by NobodyXu** [comment]
@shirshak55 See https://github.com/openssh-rust/openssh/issues/46, which track the status of Windows support in [openssh](https://github.com/openssh-rust/openssh).

It will probably land in 0.9.1

**Comment by shirshak55** [comment]
@NobodyXu thanks :) I will have keen eyes over that issue.

**Comment by NobodyXu** [comment]
@shirshak55 With the latest v0.10.0 releases, this is a no problem as you can simply pass `ChildStdin` and `ChildStdout` you obtained from `tokio` to `highlevel::Sftp::new`.
