### ISSUE TITLE
Invalid response id after closing file in blocking context

### ISSUE THREAD

**Issue by silver-ymz** [openssh-rust/openssh-sftp-client#100]
With https://github.com/openssh-rust/openssh-sftp-client/pull/98, the problem fixed by https://github.com/openssh-rust/openssh-sftp-client/pull/77 will exist. It occurs in action https://github.com/apache/incubator-opendal/actions/runs/5798363627/job/15715936917?pr=2815.

Maybe we need to find a better solution.

**Comment by NobodyXu** [comment]
There are several ways to fix this:
 - Simply issue a warning if we receive an unknown id, this is the most simple solution.
 - Store a to the runtime `tokio::runtime::Handle` in [`Auxiliary`](https://github.com/openssh-rust/openssh-sftp-client/blob/5f4799a74d67f32c06d84ffe44d67b92c290768f/src/auxiliary.rs#L22)

**Comment by silver-ymz** [comment]
I prefer the second way. Because a warning about unknown IDs may confuse the user and make debugging more difficult.

If you agree with that, I'll become work on it.

**Comment by NobodyXu** [comment]
> If you agree with that, I'll become work on it.

I do think it is more elegant way, with the `Handle` in `Auxiliary` we can also spawn new task unconditionally in `{TokioCompatFile, ReadDir}::Drop` #96
