### ISSUE TITLE
Can we implement `AsyncWrite` for `openssh_sftp_client::File`?

### ISSUE THREAD

**Issue by Xuanwo** [openssh-rust/openssh-sftp-client#109]
Hi, `File` provides most it's API through `async fn` like:

```rust
impl File
    pub async fn write(&mut self, buf: &[u8]) -> Result<usize, Error> {
        ...
    }
}
```

This make it's hard to implement `AsyncWrite` upon it: users will need to build their own state machine to make implement `poll_write` correctly.

Is it possible to add native `AsyncWrite` and `AsyncRead` support? (we already have `AsyncSeek` now).

**Comment by Xuanwo** [comment]
cc @NobodyXu and @silver-ymz, thanks in advance.

**Comment by silver-ymz** [comment]
There is [TokioCompatFile](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.TokioCompatFile.html) which provides async operations.

**Comment by Xuanwo** [comment]
> There is [TokioCompatFile](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.TokioCompatFile.html) which provides async operations.

Thanks, but is it possible to bypass the buffer logic? OpenDAL is going to have it's own general buffer in the future.

**Comment by Xuanwo** [comment]
Oh, I see. You need to capture the buffer before building future.

**Comment by Xuanwo** [comment]
> It's exactly the same as completion based async I/O so it encountered similar problems.

Yeah, I got it.

---

Thank @silver-ymz for the quick answer. And thank @NobodyXu for the explaination. My issue is fully addressed now, see you next time :laughing:
