### ISSUE TITLE
TODO: split the lowlevel and highlevel as separate crate

### ISSUE THREAD

**Issue by NobodyXu** [openssh-rust/openssh-sftp-client#11]
It seems that the API of lowlevel and highlevel aren't that tightly coupled.

Changes to the lowlevel can often be wrapped up by the highlevel, thus not posing a breaking change in the highlevel API, yet with the current model, users of the highlevel API are also forced to bump their major version number.

Splitting them into two different crates would make it possible to release these crates separately at different pace, though it would make the maintenance of it a bit harder.

If we are going with this new release model, shall we use the workspace features so that all scripts and ci setups can be shared between them, or shall we create a separate repository for the lowlevel part?

**Comment by jonhoo** [comment]
I think splitting into two crates makes a lot of sense, and if you do I'd certainly recommend doing so through a workspace.

**Comment by NobodyXu** [comment]
I actually ended up creating 3 workspaces:
 - `openssh-sftp-client-lowlevel` for the lowlevel interface
 - `openssh-sftp-error` for the error type shared by lowlevel and highlevel interface. Checkout #13 for the rationale.
 - `sftp-test-common` for building the `sftp-portable` and all the functions shared by integration tests.
