### ISSUE TITLE
`openssh-sftp-error` needs to bump major version

### ISSUE THREAD

**Issue by silver-ymz** [openssh-rust/openssh-sftp-client#112]
`openssh-sftp-error` has a break change about bumping `openssh` version in 0.3.2, but it only updates a minor version from 0.3.1.

This will result in a compilation failure, which occurs in https://github.com/apache/incubator-opendal/actions/runs/6885228025/job/18729057412

**Comment by NobodyXu** [comment]
@silver-ymz I've yanked.v0.3.2 , can you publish a new version of it and openssh-sftp-client please?

I don't have access to my laptop now.

**Comment by silver-ymz** [comment]
> can you publish a new version of it and openssh-sftp-client please?

Yes. Thank you.

**Comment by silver-ymz** [comment]
`openssh-sftp-error` is a dependency of `openssh-sftp-client-lowlevel` and `openssh-sftp-client`.  It seems that if we release a new major version of `openssh-sftp-error`, `openssh-sftp-client-lowlevel` and `openssh-sftp-client` also need to bump major version. 

Should we yank `openssh-sftp-client` v0.14.0 and release v0.14.1? When user use `openssh-sftp-client` v0.14.0, `openssh` 0.9.9 and 0.10.0 will be used at the same time to result in a compilation failure.

**Comment by NobodyXu** [comment]
@silver-ymz Yankee openssh-sftp-client v0.14.0, there's no v0.14.1

**Comment by silver-ymz** [comment]
done in #113, https://crates.io/crates/openssh-sftp-client/versions
