### ISSUE TITLE
unix only ?

### ISSUE THREAD

**Issue by paq1** [openssh-rust/openssh-sftp-client#115]
i have this error on window at compilation time : error[E0433]: failed to resolve: could not find `unix` in `os`

**Comment by NobodyXu** [comment]
IIRC unix is only used in test code.

Do you have the output and the command you use?

**Comment by NobodyXu** [comment]
FYI openssh-sftp-client compiles on windows, in our [CI](https://github.com/openssh-rust/openssh-sftp-client/actions/runs/8720590718/job/23922442420)

If you enable feature `openssh` though, it would pull in `openssh` crate, which is unix-only.
