### ISSUE TITLE
`check.sh` would fail on Mac systems

### ISSUE THREAD

**Issue by xis19** [openssh-rust/openssh-sftp-client#120]
`check.sh`, which depends on `rsync`, will not work on Mac since `rsync` on mac has version 2.6.9 which was built over 20 years ago.

**Comment by NobodyXu** [comment]
Does homebrew version of rsync work?

It works on my mac and I'm pretty sure I installed rsync via homebrew.

If it does, I can update the README for macOS devs.

**Comment by xis19** [comment]
I am using the rsync from the system. So it is expected to be very old...

**Comment by NobodyXu** [comment]
Yeah that's a pity, does homebrew rsync work for you?
