### ISSUE TITLE
Directory can't be iterated

### ISSUE THREAD

**Issue by kanpov** [openssh-rust/openssh-sftp-client#129]
When trying to await ReadDir, an error is shown that ReadDir is not a future?

**Comment by kanpov** [comment]
`for_each` doesn't work at all as well: ReadDir is not an iterator

**Comment by kanpov** [comment]
Using `tokio_stream` with `read_dir.next().await` produces an error: `PhantomPinned cannot be unpinned`. So even an extra crate doesn't help?

**Comment by NobodyXu** [comment]
[`futures_util::StreamExt`](https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html) has a lot of helpful methods like `filter`, `map`, `collect`, I think it might make it easier for you.
