### ISSUE TITLE
Trying to create a file over SFTP results in BackgroundTaskFailure

### ISSUE THREAD

**Issue by kanpov** [openssh-rust/openssh-sftp-client#130]
```called `Result::unwrap()` on an `Err` value: BackgroundTaskFailure("read/flush task failed")```

**Comment by kanpov** [comment]
Manually trying to create the file via something like `sftp.options().create_new(true).open(&path).await.unwrap();` causes the same issue

**Comment by kanpov** [comment]
I was using a dockerized sshd, but even with a non-dockerized one on my LAN the same issue appears, seems like the library is at fault

**Comment by NobodyXu** [comment]
It looks like it cannot read/flush.

Can you try launchjng `sftp` via ssh directly?

Perhaps your sshd configuration disallows sftp-subsystem?

**Comment by NobodyXu** [comment]
BTW there's a feature `tracing`, can you try turning it on?

I recommend to use it with [tracing-appendet](https://docs.rs/tracing-appender/latest/tracing_appender/) and [tracing-subscriber](https://docs.rs/tracing-subscriber/):

```rust
let (non_blocking, _guard) = tracing_appender::non_blocking(std::io::stdout());
tracing_subscriber::fmt()
    .with_writer(non_blocking)
    .init();
```

**Comment by kanpov** [comment]
> It looks like it cannot read/flush.
> 
> Can you try launchjng `sftp` via ssh directly?
> 
> Perhaps your sshd configuration disallows sftp-subsystem?

Sftp is definitely enabled and works just fine over russh:

```dockerfile
FROM debian:latest

RUN apt-get update && apt-get install -y openssh-server curl
RUN mkdir /var/run/sshd
RUN echo 'root:root123' | chpasswd
RUN echo 'PermitRootLogin yes\nSubsystem sftp internal-sftp' > /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
```

**Comment by kanpov** [comment]
Heavily doubt I'm doing something wrong with initialization of `Session` and `Sftp`:

```rust
    let builder = SessionBuilder::default();
    let str_dest = format!("ssh://root@localhost:{}", ssh_port);
    let (builder, dest) = builder.resolve(str_dest.as_str());
    let tempdir = builder.launch_master(dest).await?;
    let session = Session::new_native_mux(tempdir);

    Ok(session)
```

```rust
        let mut child = owned_session
            .subsystem("sftp")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .await
            .expect("Could not make sftp child");
        let owned_sftp = Sftp::new(
            child.stdin().take().unwrap(),
            child.stdout().take().unwrap(),
            SftpOptions::default(),
        )
        .await
        .expect("Could not make sftp");
```

**Comment by kanpov** [comment]
@NobodyXu `Sftp::from_session`  from the `openssh` feature actually works, but this raises two questions:

1. Why does `from_session` need to move in the `Session`? Why can't the connection be used for both SSH and SFTP?
2. Why does `Sftp::new` as shown above not work?

**Comment by kanpov** [comment]
Because of the moving mentioned above, a test setup for SSH and SFTP needs 4 connections to the same sshd, which I find absurd. Is it really necessary?

**Comment by NobodyXu** [comment]
> Why does from_session need to move in the Session? Why can't the connection be used for both SSH and SFTP?

It can be avoided using [`openssh::Session::to_subsystem`](https://docs.rs/openssh/latest/openssh/struct.Session.html#method.to_subsystem)

I will open a PR for it

> Why does Sftp::new as shown above not work?


Might be because the child is dropped while the sftp is still there?

**Comment by kanpov** [comment]
> Might be because the child is dropped while the sftp is still there?

Actually probably that, will test it
