### ISSUE TITLE
Drop semantics for files

### ISSUE THREAD

**Issue by kanpov** [openssh-rust/openssh-sftp-client#132]
A file needs to be closed manually via an await to `close()`, which in my opinion doesn't really fit Rust's drop semantics that are used in I/O as well by libraries such as russh and tokio-fs.
So would it be possible for Drop to be implemented for File and TokioCompatFile that would perform the necessary releasing in accordance with drop semantics automatically?

**Comment by kanpov** [comment]
Considering this is a tokio-only library and closing absolutely requires async, imo it'd make sense to spawn during a drop and defer the async close call

**Comment by kanpov** [comment]
Similarly, imo Drop is needed for Session and Sftp

**Comment by NobodyXu** [comment]
> So would it be possible for Drop to be implemented for File and TokioCompatFile that would perform the necessary releasing in accordance with drop semantics automatically?

It's already implemented, `File` uses another internal type that implements `Drop` using `tokio::spawn`

For `TokioCompatFile`:

https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.TokioCompatFile.html#impl-Drop-for-TokioCompatFile

**Comment by NobodyXu** [comment]
One of the problems with `File` API is that they take mutable references instead of immutable, despite that it has almost no state.

**Comment by NobodyXu** [comment]
> Similarly, imo Drop is needed for Session and Sftp

It's already defined, otherwise the background task would be around forever until you dropped the child.
