### ISSUE TITLE
flush_interval set to 0 panics

### ISSUE THREAD

**Issue by DoumanAsh** [openssh-rust/openssh-sftp-client#135]
https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/struct.SftpOptions.html#method.flush_interval

According to documentation:

> If flush_interval is set to 0, then every packet is flushed immediately.

But in reality it will attempt to set up periodic timer with duration zero:
https://github.com/openssh-rust/openssh-sftp-client/blob/main/src/tasks.rs#L68

**Comment by NobodyXu** [comment]
Thanks, looks like I misunderstood `tokio::time::interval`.

would open a PR later to fix this

**Comment by NobodyXu** [comment]
Released a new version to fix this
