### ISSUE TITLE
chore: prepare for v0.11.0 release

### ISSUE THREAD

**Issue by NobodyXu** [openssh-rust/openssh-sftp-client#22]
With #9 and #11 done, now we are almost ready for v0.11.0 release.

Since this will be a new major release, I would like to clean up the API and remove anything that will be confusing.

@jonhoo Can you help me with this, by looking at the public APIs exposed by openssh-sftp-client and see if there is anything you would like to remove or add?

**Comment by NobodyXu** [comment]
Released openssh-sftp-error v0.1.0, openssh-sftp-client-lowlevel v0.1.0

**Comment by NobodyXu** [comment]
Released openssh-sftp-client v0.11.0-rc.1

**Comment by NobodyXu** [comment]
[openssh-sftp-client v0.11.0-rc.2](https://docs.rs/openssh-sftp-client/0.11.0-rc.2/openssh_sftp_client/) is released

**Comment by NobodyXu** [comment]
[openssh-sftp-client v0.11.0-rc.3](https://docs.rs/openssh-sftp-client/0.11.0-rc.3/openssh_sftp_client/) is released!

**Comment by jonhoo** [comment]
Given that we're still 0.x I think it's okay to do the release and then iterate based on feedback. Manual inspection is only going to get us so far :)

**Comment by NobodyXu** [comment]
@jonhoo [openssh-sftp-client 0.11.0](https://docs.rs/openssh-sftp-client/0.11.0/openssh_sftp_client/) has released!
