### ISSUE TITLE
Move upstream dependency into this org

### ISSUE THREAD

**Issue by NobodyXu** [openssh-rust/openssh-sftp-client#33]
This crate has two dependencies that worth putting into this org:
 - [`awaitable`](https://github.com/NobodyXu/awaitable) an awaitable type to convey input to the `ReadEnd` and then get the response from it.
 - [`concurrent_arena`] concurrent arena that uses a `u32` as key. P.S. ~~I'm now working on avoiding this dependency on `openssh_sftp_client_lowlevel`, but `openssh_sftp_client` would still depend on it. It requires GAT to parameterize it, so it will stay as-is for now.~~ It took too much effort and doesn't have much benefit, so I gave it up.

These two crates are owned by me and created specifically for `openssh-sftp-client` and there is no other dependent of it right now.

I'd like to move these two repos into this org and I'd like your review on [`concurrent_arena`] since it contains some `unsafe` code and invovles concurrency @jonhoo ,

[`concurrent_arena`]: https://github.com/NobodyXu/concurrent_arena

**Comment by jonhoo** [comment]
I don't think we should overload this org too much with crates that, while we're the only users of them, are intended for broader use.

Unfortunately, I don't have the spare cycles at the moment to do a proper review of `concurrent_arena` at the moment :disappointed:

**Comment by NobodyXu** [comment]
> I don't think we should overload this org too much with crates that, while we're the only users of them, are intended for broader use.

Sounds reasonable

> Unfortunately, I don't have the spare cycles at the moment to do a proper review of `concurrent_arena` at the moment 😞

No worries, feel free to open issue in `concurrent_arena` if you find any bug or design problem.
