### ISSUE TITLE
Something in `Sftp::new` does not implement `Send`

### ISSUE THREAD

**Issue by mihirsamdarshi** [openssh-rust/openssh-sftp-client#54]
### Description
I am trying to use `Sftp` in an app that I am developing with [`tauri`](https://github.com/tauri-apps/tauri). `tauri` is an Electron alternative which haș the concept of commands, which allow the frontend to invoke some functionality from the backend. My use case of this crate involves uploading some file to a remote server upon some user's invocation. However, `tauri::commands` must implement `Send`. I am getting an error that state's that `Send` is not implemented for the `Id` newtype in `openssh-sftp-client`.

I was wondering if you could help me figure out a) where exactly this error was coming from, b) if this was fixable, and c) what we/I can do or contribute to fix it.

### Full error message from  `rustc`/`tauri`

```
error: future cannot be sent between threads safely
   --> src/ssh/commands.rs:55:1
    |
55  |   #[tauri::command]
    |   ^^^^^^^^^^^^^^^^^
    |   |
    |   future returned by `send_backup_command` is not `Send`
    |   in this expansion of `ssh::commands::__cmd__send_backup_command!` (#2)
    |
   ::: /Users/msamdars/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-macros-1.1.1/src/lib.rs:49:1
    |
49  |   pub fn generate_handler(item: TokenStream) -> TokenStream {
    |   --------------------------------------------------------- in this expansion of `tauri::generate_handler!` (#1)
    |
   ::: src/main.rs:491:25
    |
491 |           .invoke_handler(tauri::generate_handler![
    |  _________________________-
492 | |             persist_state_to_disk,
493 | |             load_state_from_disk,
494 | |             load_privacy_policy_accepted,
...   |
546 | |             upload::gcp::upload_file_gcs,
547 | |         ])
    | |         -
    | |         |
    | |_________in this macro invocation (#1)
    |           in this macro invocation (#2)
    |
    = help: the trait `std::marker::Send` is not implemented for `dyn futures::Future<Output = std::result::Result<(openssh_sftp_client_lowlevel::awaitable_responses::Id<bytes::bytes_mut::BytesMut>, openssh_sftp_protocol::response::Limits), openssh_sftp_error::Error>>`
note: required by a bound in `tauri::command::private::ResultFutureTag::future`
   --> /Users/msamdars/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.1.1/src/command.rs:289:42
    |
289 |       F: Future<Output = Result<T, E>> + Send,
    |                                          ^^^^ required by this bound in `tauri::command::private::ResultFutureTag::future`
```

### Reproduction

1) Make sure you have the [necessary prerequisites](https://tauri.app/v1/guides/getting-started/prerequisites)
2) Run `yarn create tauri-app` and choose your preferred front-end stack (since this error occurs in the backend, any frontend will do)
3) Replace your `src-tauri/src/main.rs` file with the following:
```rust
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use openssh::Stdio;
use openssh_sftp_client::{Sftp, SftpOptions};

const PRIVATE_KEY_PATH: &str = "";
const USERNAME: &str = "";
const IP: &str = "";
const PORT: u16 = 22;

async fn sftp_open() -> anyhow::Result<Sftp> {
    let sess = openssh::SessionBuilder::default()
    .user(USERNAME.to_string())
        .port(PORT)
        .keyfile(PRIVATE_KEY_PATH)
        .control_directory(std::env::temp_dir())
        .connect(IP)
        .await?;

    // Request a SFTP subsystem, and wait until it completes.
    let mut child = sess
        .subsystem("sftp")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .await?;

    let sftp = Sftp::new(
        child.stdin().take().unwrap(),
        child.stdout().take().unwrap(),
        SftpOptions::default(),
    )
    .await?;

    Ok(sftp)
}

#[tauri::command]
async fn upload_new_file() -> Result<(), String> {
    let sftp = sftp_open().await.map_err(|e| e.to_string())?;
    let mut file = sftp.create("test.txt").await.map_err(|e| e.to_string())?;

    file.write_all(b"hello world").await.map_err(|e| e.to_string())?;
    file.close().await.map_err(|e| e.to_string())?;
    sftp.close().await.map_err(|e| e.to_string())?;
    Ok(())
}

fn main() {
    tauri::Builder::default()
    .invoke_handler(tauri::generate_handler![upload_new_file])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
4) Run `yarn build`, and then `yarn tauri dev` to see the error

**Comment by NobodyXu** [comment]
Thanks for reporting!
I just briefly look at source code of `Sftp::new` and honestly I'm not sure which function is the culprit.
I would have to further investigate the problem.

> I am getting an error that state's that Send is not implemented for the Id newtype in openssh-sftp-client.

[`openssh_sftp_client_lowlevel::Id`](https://docs.rs/openssh-sftp-client-lowlevel/latest/openssh_sftp_client_lowlevel/struct.Id.html), which is used by `openssh-sftp-client`, implements `Send`.

**Comment by NobodyXu** [comment]
I have reproduced the error and I have confirmed that it indeed is caused by `Sftp::new`.

**Comment by NobodyXu** [comment]
@mihirsamdarshi I've fixed this in the linked PR.

**Comment by NobodyXu** [comment]
@mihirsamdarshi openssh-sftp-client v0.12.1 has released, the API doesn't change except for `Sftp::new` (and probably other `async` functions, I didn't check for that) now returns futures that implement `Send`.

**Comment by NobodyXu** [comment]
[docs for openssh-sftp-client v0.12.1](https://docs.rs/openssh-sftp-client/0.12.1/openssh_sftp_client/) is ready now.

**Comment by mihirsamdarshi** [comment]
thanks so much @NobodyXu!
