### ISSUE TITLE
Misleading naming of `file::write` and `file::write_all`

### ISSUE THREAD

**Issue by Mastermindaxe** [openssh-rust/openssh-sftp-client#60]
Hi there,
I've stumbled upon a bug in our code where we used `file::write` instead of `file::write_all` and our file got truncated without us noticing because we didn't read the result success case but only the error.

Is there any way you would consider a naming change as the documentation claims to be closely modelled to the standard library? The standard library uses [`std::fs::write`](https://doc.rust-lang.org/std/fs/fn.write.html) to write all the contents of a slice.

This might be confusing to other users as well. What do you and other people think?

**Comment by NobodyXu** [comment]
Well, there's no `file::write` function or `file::write_all` function, it's rather `File::write` and `File::write_all` associated function.

Both of them are associated function that models closely after `<std::File as Write>::write` and `<std::File as Write>::write_all`, so I think the naming is OK.

**Comment by NobodyXu** [comment]
> Would you be willing to accept a PR that clarifies these differences in the documentation

I would definitely love so!

**Comment by NobodyXu** [comment]
@Mastermindaxe I've fixed the doc in #66

**Comment by Mastermindaxe** [comment]
Wonderful! Cheers. There's a small grammar mistake in the docs:
```
NOTE that this API might only writes part of the `buf`.
```
should be 
```
NOTE that this API might only write part of the `buf`.
```

**Comment by NobodyXu** [comment]
Thanks!

I've fixed it.
