### ISSUE TITLE
How can I upload big File

### ISSUE THREAD

**Issue by andrew121410** [openssh-rust/openssh-sftp-client#61]
Is there a way instead of loading up a huge file in RAM to upload, how can I split the file in parts to upload?

**Comment by NobodyXu** [comment]
You can use [`File::write`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.File.html#method.write) or [`File::write_zero_copy`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.File.html#method.write_zero_copy) to upload piece by piece.

There is also [`TokioCompatFile`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.TokioCompatFile.html) which implements `tokio::io::AsyncWrite` that you can use with `tokio::io::copy` or `tokio::io::copy_buf`.

**Comment by andrew121410** [comment]
Thank you!
