### ISSUE TITLE
Incorrect behavior about `AsyncSeek` of `TokioCompatFile`

### ISSUE THREAD

**Issue by silver-ymz** [openssh-rust/openssh-sftp-client#80]
Sometimes `AsyncSeek` to `TokioCompatFile` will set the offset to the wrong place. This error occurs in https://github.com/apache/incubator-opendal/pull/2263 https://github.com/apache/incubator-opendal/actions/runs/4976970726/jobs/8905529556

I guess the problem is about https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L354

https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L383-L391
When the offset amount is larger than `buffer.len()`, it will only offset to the end of buffer.

I haven't found the code which can reproduce stably. I will try to fix it these days.

**Comment by NobodyXu** [comment]
Note that [File::start_seek](https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/mod.rs#L750) does not support SeekFrom::End, since I'm not sure how to implement it in a race-free manner

**Comment by NobodyXu** [comment]
Also, in https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L354

offset can be larger than the self.buffer.len(), this is a UB according to AsyncBufRead interface.

**Comment by NobodyXu** [comment]
However, our AsyncBufRead impl is also wrong https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L383-L391

It should panic if amt is more than self.buffer.len()

**Comment by NobodyXu** [comment]
What I suggest you to do is to advance the buffer and increase offset manually in https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L354

**Comment by silver-ymz** [comment]
> What I suggest you to do is to advance the buffer and increase offset manually in

I think so. I'll complete it tomorrow.

**Comment by NobodyXu** [comment]
> > What I suggest you to do is to advance the buffer and increase offset manually in
> 
> I think so. I'll complete it tomorrow.

It will also be great if you can fix <TokioCompatFile as AsyncBuf>::consume
