### ISSUE TITLE
TokioCompatFile has an infinite write buffer size, which is unexpected 

### ISSUE THREAD

**Issue by reivilibre** [openssh-rust/openssh-sftp-client#89]
From what I can tell, `TokioCompatFile` will sneakily buffer up an unlimited number of bytes into memory and doesn't apply any backpressure when writing.

The `poll_write` implementation will spawn new write requests and from what I can see always returns `Poll::Ready` — never `Poll::Pending`.

Other than leading to an unexpectedly high write throughput to start with, then an unexpectedly slow final `flush()`, this also results in very high / unbounded memory usage. :)

The best workaround for library users I can find today is to `flush()` every so often, but this worsens performance because it waits for the *whole* write request queue to be drained, when it is actually quite healthy to have *some* write requests in-flight.

I think a better approach would be for `poll_write` to return `Poll::Pending` if there are too many write requests in the queue (counted either by number of requests or number of bytes), then to wake the context once that number decreases beneath a threshold.

**Comment by NobodyXu** [comment]
Thanks!

This is indeed something it can improve, for the write requests limit, I have two ideas:
 - We can use the limit passed in to [`SftpOptions::max_pending_requests`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/struct.SftpOptions.html#method.max_pending_requests), this would yield the best performance without adding more options to configure
 - We can add a new per-`TokioCompatFile` limit, this would make tuning performance much easier, but add more configuration option and might be harder to use

@silver-ymz What's your thoughts on this?

**Comment by silver-ymz** [comment]
https://github.com/openssh-rust/openssh-sftp-client/blob/a31798d30fce4024183a19810c987d48c2e7e459/src/file/tokio_compat_file.rs#L479-L481

https://github.com/openssh-rust/openssh-sftp-client/blob/a31798d30fce4024183a19810c987d48c2e7e459/src/file/tokio_compat_file.rs#L54

The `poll_write` implementation will call `wakeup_flush_task` so that it will flush automatically. Since that, library users don't need to call `flush()` themselves.

If users want to change the limit, the can directly change [`SftpOptions::max_pending_requests`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/struct.SftpOptions.html#method.max_pending_requests) or [`SftpOptions::flush_interval`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/struct.SftpOptions.html#method.flush_interval)

**Comment by NobodyXu** [comment]
Yep, but from @reivilibre 

> The poll_write implementation will spawn new write requests and from what I can see always returns Poll::Ready — never Poll::Pending.
>
> Other than leading to an unexpectedly high write throughput to start with, then an unexpectedly slow final flush(), this also results in very high / unbounded memory usage. :)

The unbounded memory usage is indeed worrisome 

Maybe we should at least return `Poll::Pending` occasionally to avoid too much memory usage?

**Comment by silver-ymz** [comment]
Yes, we can set a max memory usage for `AsyncCompatFile`. However, the unbounded memory usage problem also exists in `File::write`, which may be difficult to solve. We can't return `Poll::Pending` for it, but returning an error directly may be a bit unfriendly.

**Comment by NobodyXu** [comment]
> Yes, we can set a max memory usage for AsyncCompatFile.

IMHO it's best to follow the settings in `SftpOptions`: If the internal requests buffer is full, wait for them to be flushed before continue.

Once they are flushed, the memory is freed up and we can continue to send more requests.

> However, the unbounded memory usage problem also exists in `File::write`

[`File::write`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.File.html#method.write) wait for the write to finish before returning, so it does not have the unbounded memory usage.

We actually provide another API, [`File::write_zero_copy`](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.File.html#method.write_zero_copy) for zero copy writing.

**Comment by silver-ymz** [comment]
> [File::write](https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/file/struct.File.html#method.write) wait for the write to finish before returning, so it does not have the unbounded memory usage.

Yes, you are right. Sorry for misunderstanding the code.

> Perhaps it would be better to add a new option to SftpOptions to limit maximum memory usage of TokioCompatFile.
I think it makes more sense since each individual request can contain up to near u32::MAX amount of data

I agree with it. It's more useful to provide a new option to limit maximum memory usage of `TokioCompatFile`.

**Comment by NobodyXu** [comment]
I was a little bit busy, I will probably do this tomorrow.
But in case I didn't have time to do so, feel free to submit a patch @silver-ymz 

I've removed the assignment since I might be too busy to do this.

**Comment by reivilibre** [comment]
Thanks for adding the ability to add a limit.

I'm not sure the current default of `usize::MAX` is the best — I think it would be quite surprising to new users of the library — however I am grateful that you added this option for me and I am happy to say that my program no longer eats all the RAM :).

**Comment by NobodyXu** [comment]
> I'm not sure the current default of `usize::MAX` is the best — I think it would be quite surprising to new users of the library

I've opened #103 to change default to 640KB.

> — however I am grateful that you added this option for me and I am happy to say that my program no longer eats all the RAM :).

That's good to hear!
