### ISSUE TITLE
exaxmples/ folder demonstrating how to use this crate.

### ISSUE THREAD

**Issue by rukai** [openssh-rust/openssh-sftp-client#93]
There are tests here but reading them is just leaving me more confused: https://github.com/openssh-rust/openssh-sftp-client/blob/main/tests/highlevel.rs
It seems like we are spawning a server but I thought this was a client library? 

I think a simple example demonstrating how to use this library in the most common use case would go a long way.

**Comment by NobodyXu** [comment]
>  It seems like we are spawning a server but I thought this was a client library?

`openssh_sftp_client::Sftp::new` calls `tokio::spawn` to create background write/flush and read task, and communicates with it via channel.

So you can say it is indeed a bit like spawning a server.

The rationale for this is that you can issue multiple sftp requests in parallel and `.await` on them in parallel, in that case doing the read/write in each operation will require a lot of synchronization.

> I think a simple example demonstrating how to use this library in the most common use case would go a long way.

Thanks, that's a good idea.
I will add that and @silver-ymz feel free to also add yours if you have time.
